language: python

before_install: pip install requests
install: pip install rasterio
script: echo HELLO

jobs:
  include:
    - stage: test
      before_install: skip
      install: skip
      script:
        - python -c "import requests; print(requests.__version__)"
        - python -c "import rasterio; print(rasterio.__version__)"
    - stage: test
      install: skip
      script:
        - python -c "import requests; print(requests.__version__)"
        - python -c "import rasterio; print(rasterio.__version__)"
    - stage: test
      script:
        - python -c "import requests; print(requests.__version__)"
        - python -c "import rasterio; print(rasterio.__version__)"
    # - stage: deploy
    #   script: echo deploy stage 1
