os: osx
language: generic

jobs:
  include:
    - stage: test
      name: "Manual brew install"
      script: echo {} | jq .
    - stage: test
      name: "Addon brew install"
      addons:
        homebrew:
          packages: jq
      script: echo {} | jq .
