language: python

jobs:
  include:
    - stage: test
      name: "Manual brew install"
      os: osx
      language: generic
      script: echo {} | jq .
    - stage: test
      name: "Addon brew install"
      addons:
        homebrew:
          packages: jq
      script: echo {} | jq .
