language: python

jobs:
  include:
    - stage: test
      name: "Manual brew install"
      os: osx
      language: generic
      script: echo '{"foo": 0}' | jq .
    - stage: test
      name: "Addon brew install"
      addons:
        homebrew:
          packages: jq
      script: echo '{"foo": 0}' | jq .
