language: python

jobs:
  include:
    - stage: packaging
      script:
        - echo HELLO!!!
    - stage: deploy
      if: tag IS present
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: glostis
          password:
            blabla
          server: https://test.pypi.org/legacy/
