language: python

install: pip install requests

jobs:
  include:
    - stage: test
      install: skip
      script: python -c "import requests; print(requests.__version__)"
    - stage: test
      script: python -c "import requests; print(requests.__version__)"
    # - stage: deploy
    #   script: echo deploy stage 1
