os: osx
language: generic

script:
  - brew --version
  - brew bundle

jobs:
  include:
    - name: "osx_image: xcode11"
      osx_image: xcode11
    - name: "osx_image: xcode10.2"
      osx_image: xcode10.2
    - name: "osx_image: xcode10.1"
      osx_image: xcode10.1
    - name: "osx_image: xcode10"
      osx_image: xcode10
    - name: "osx_image: xcode9.4"
      osx_image: xcode9.4
    - name: "osx_image: xcode9.3"
      osx_image: xcode9.3
    - name: "osx_image: xcode9.2"
      osx_image: xcode9.2
    - name: "osx_image: xcode9.1"
      osx_image: xcode9.1
    - name: "osx_image: xcode9"
      osx_image: xcode9
    - name: "osx_image: xcode8.3"
      osx_image: xcode8.3
    - name: "osx_image: xcode8"
      osx_image: xcode8
    - name: "osx_image: xcode7.3"
      osx_image: xcode7.3
    - name: "osx_image: xcode6.4"
      osx_image: xcode6.4
