language: python

before_install: pip install requests
install: pip install rasterio

jobs:
  include:
    - stage: test
      python: 2.7
      script: python -v
    - stage: test
      python: 3.7
      script: python -v
    # - stage: deploy
    #   script: echo deploy stage 1
