os: osx
language: generic

script: brew --version

jobs:
  include:
    - name: "osx_image: xcode11.3"
      osx_image: xcode11.3
    - name: "osx_image: xcode11.2"
      osx_image: xcode11.2
    - name: "osx_image: xcode11.1"
      osx_image: xcode11.1
    - name: "osx_image: xcode11"
      osx_image: xcode11
    - name: "osx_image: xcode10.3"
      osx_image: xcode10.3
    - name: "osx_image: xcode10.2"
      osx_image: xcode10.2
    - name: "osx_image: xcode10.1"
      osx_image: xcode10.1
    - name: "osx_image: xcode10"
      osx_image: xcode10
    - name: "osx_image: xcode9.4"
      osx_image: xcode9.4
